/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        // Primary Brand Colors
        primary: {
          50: 'var(--color-primary-50)',
          100: 'var(--color-primary-100)',
          200: 'var(--color-primary-200)',
          300: 'var(--color-primary-300)',
          400: 'var(--color-primary-400)',
          500: 'var(--color-primary-500)',
          600: 'var(--color-primary-600)',
          700: 'var(--color-primary-700)',
          800: 'var(--color-primary-800)',
          900: 'var(--color-primary-900)',
        },
        // Secondary Brand Colors
        secondary: {
          50: 'var(--color-secondary-50)',
          100: 'var(--color-secondary-100)',
          200: 'var(--color-secondary-200)',
          300: 'var(--color-secondary-300)',
          400: 'var(--color-secondary-400)',
          500: 'var(--color-secondary-500)',
          600: 'var(--color-secondary-600)',
          700: 'var(--color-secondary-700)',
          800: 'var(--color-secondary-800)',
          900: 'var(--color-secondary-900)',
        },
        // Accent Colors
        accent: {
          50: 'var(--color-accent-50)',
          100: 'var(--color-accent-100)',
          200: 'var(--color-accent-200)',
          300: 'var(--color-accent-300)',
          400: 'var(--color-accent-400)',
          500: 'var(--color-accent-500)',
          600: 'var(--color-accent-600)',
          700: 'var(--color-accent-700)',
          800: 'var(--color-accent-800)',
          900: 'var(--color-accent-900)',
        },
        // Success Colors
        success: {
          50: 'var(--color-success-50)',
          100: 'var(--color-success-100)',
          200: 'var(--color-success-200)',
          300: 'var(--color-success-300)',
          400: 'var(--color-success-400)',
          500: 'var(--color-success-500)',
          600: 'var(--color-success-600)',
          700: 'var(--color-success-700)',
          800: 'var(--color-success-800)',
          900: 'var(--color-success-900)',
        },
        // Warning Colors
        warning: {
          50: 'var(--color-warning-50)',
          100: 'var(--color-warning-100)',
          200: 'var(--color-warning-200)',
          300: 'var(--color-warning-300)',
          400: 'var(--color-warning-400)',
          500: 'var(--color-warning-500)',
          600: 'var(--color-warning-600)',
          700: 'var(--color-warning-700)',
          800: 'var(--color-warning-800)',
          900: 'var(--color-warning-900)',
        },
        // Error Colors
        error: {
          50: 'var(--color-error-50)',
          100: 'var(--color-error-100)',
          200: 'var(--color-error-200)',
          300: 'var(--color-error-300)',
          400: 'var(--color-error-400)',
          500: 'var(--color-error-500)',
          600: 'var(--color-error-600)',
          700: 'var(--color-error-700)',
          800: 'var(--color-error-800)',
          900: 'var(--color-error-900)',
        },
        // Neutral Colors
        neutral: {
          0: 'var(--color-neutral-0)',
          50: 'var(--color-neutral-50)',
          100: 'var(--color-neutral-100)',
          200: 'var(--color-neutral-200)',
          300: 'var(--color-neutral-300)',
          400: 'var(--color-neutral-400)',
          500: 'var(--color-neutral-500)',
          600: 'var(--color-neutral-600)',
          700: 'var(--color-neutral-700)',
          800: 'var(--color-neutral-800)',
          900: 'var(--color-neutral-900)',
          950: 'var(--color-neutral-950)',
        },
      },
      fontSize: {
        'scale-xs': ['var(--font-size-xs)', { lineHeight: 'var(--line-height-xs)' }],
        'scale-sm': ['var(--font-size-sm)', { lineHeight: 'var(--line-height-sm)' }],
        'scale-base': ['var(--font-size-base)', { lineHeight: 'var(--line-height-base)' }],
        'scale-lg': ['var(--font-size-lg)', { lineHeight: 'var(--line-height-lg)' }],
        'scale-xl': ['var(--font-size-xl)', { lineHeight: 'var(--line-height-xl)' }],
        'scale-2xl': ['var(--font-size-2xl)', { lineHeight: 'var(--line-height-2xl)' }],
        'scale-3xl': ['var(--font-size-3xl)', { lineHeight: 'var(--line-height-3xl)' }],
        'scale-4xl': ['var(--font-size-4xl)', { lineHeight: 'var(--line-height-4xl)' }],
        'scale-5xl': ['var(--font-size-5xl)', { lineHeight: 'var(--line-height-5xl)' }],
      },
      fontWeight: {
        'weight-normal': 'var(--font-weight-normal)',
        'weight-medium': 'var(--font-weight-medium)',
        'weight-bold': 'var(--font-weight-bold)',
      },
      spacing: {
        'space-1': 'var(--spacing-1)',
        'space-2': 'var(--spacing-2)',
        'space-3': 'var(--spacing-3)',
        'space-4': 'var(--spacing-4)',
        'space-5': 'var(--spacing-5)',
        'space-6': 'var(--spacing-6)',
        'space-8': 'var(--spacing-8)',
        'space-10': 'var(--spacing-10)',
        'space-12': 'var(--spacing-12)',
        'space-16': 'var(--spacing-16)',
        'space-20': 'var(--spacing-20)',
        'space-24': 'var(--spacing-24)',
        'space-32': 'var(--spacing-32)',
      },
      borderRadius: {
        'radius-sm': 'var(--border-radius-sm)',
        'radius-md': 'var(--border-radius-md)',
        'radius-lg': 'var(--border-radius-lg)',
        'radius-xl': 'var(--border-radius-xl)',
        'radius-2xl': 'var(--border-radius-2xl)',
      },
      boxShadow: {
        'shadow-sm': 'var(--shadow-sm)',
        'shadow-md': 'var(--shadow-md)',
        'shadow-lg': 'var(--shadow-lg)',
        'shadow-xl': 'var(--shadow-xl)',
      },
    },
  },
  plugins: [],
};